In [18]:
# Random Forest Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [19]:
# Importing the dataset
dataset = pd.read_csv('/content/HousePrices_HalfMil.csv')


In [20]:
dataset.head()

Area  Garage  FirePlace  Baths  White Marble  Black Marble  Indian Marble  \
0   164       2          0      2             0             1              0   
1    84       2          0      4             0             0              1   
2   190       2          4      4             1             0              0   
3    75       2          4      4             0             0              1   
4   148       1          4      2             1             0              0   

   Floors  City  Solar  Electric  Fiber  Glass Doors  Swiming Pool  Garden  \
0       0     3      1         1      1            1             0       0   
1       1     2      0         0      0            1             1       1   
2       0     2      0         0      1            0             0       0   
3       1     1      1         1      1            1             1       1   
4       1     2      1         0      0            1             1       1   

   Prices  
0   43800  
1   37550  
2   49500  
3   50075  
4   52400

In [21]:
X = dataset.drop('Prices', axis=1)
y = dataset['Prices']

In [22]:
X.shape

(500000, 15)

In [23]:
y.shape

(500000,)

In [27]:
from sklearn.model_selection import train_test_split
##X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state = 0)

Decision Tree Regressor

In [28]:
# import the regressor
from sklearn.tree import DecisionTreeRegressor

# create a regressor object
regressor1 = DecisionTreeRegressor(random_state = 0)

# fit the regressor with X and Y data
regressor1.fit(X_train,y_train)

DecisionTreeRegressor(random_state=0)

In [29]:
y_pred1 = regressor1.predict(X_test)

In [30]:
mse1 = mean_squared_error(y_test, y_pred1)
mae2 = mean_absolute_error(y_test, y_pred1)

#Print the results
print('Decision Tree Regressorn:')
print('MSE:', mse1)
print('MAE:', mae2)

Decision Tree Regressorn:
MSE: 109032.24375
MAE: 234.78575


In [31]:
regressor1.score(X_test, y_test)

0.9992544207655191

In [32]:
# import export_graphviz
from sklearn.tree import export_graphviz

# export the decision tree to a tree.dot file
# for visualizing the plot easily anywhere
export_graphviz(regressor1, out_file ='tree.png')

In [33]:
! dot -Tpdf tree.dot -o tree.pdf

Error: dot: can't open tree.dot


In [34]:
! xdot tree.dot

/bin/bash: line 1: xdot: command not found


In [35]:
! cd

In [36]:
!dot -Tpng tree.dot -o tree1.png

Error: dot: can't open tree.dot


Random Forest Regression

In [37]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [30]:
# Predicting a new result
#y_pred = regressor.predict([[6.5,]])

In [38]:
y_pred = regressor.predict(X_test)

In [39]:

#Calculate the MSE and MAE
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
#Print the results
print('Random Forest Regression:')
print('MSE:', mse)
print('MAE:', mae)

Random Forest Regression:
MSE: 62143.41875
MAE: 190.82215


In [40]:
regressor.score(X_test, y_test)

0.9995750537548701

In [41]:
regressor2 = RandomForestRegressor(n_estimators = 50, random_state = 0,max_depth=10)
regressor2.fit(X_train, y_train)

RandomForestRegressor(max_depth=10, n_estimators=50, random_state=0)

In [48]:
y_pred2 = regressor2.predict(X_test)
y_pred2

array([28788.1908115 , 41614.32525288, 55128.57902759, ...,
       40178.18314279, 55382.18723885, 42334.03827799])

In [36]:
#Calculate the MSE and MAE
mse = mean_squared_error(y_test, y_pred2)
mae = mean_absolute_error(y_test, y_pred2)
#Print the results
print('Random Forest Regression:')
print('MSE:', mse)
print('MAE:', mae)

Random Forest Regression:
MSE: 2135714.6887288694
MAE: 1172.0811133493917


In [ ]:
print(regressor2.score(X_train, y_train))
print(regressor2.score(X_test, y_test))

0.9859819125834846
0.9853956548271801


In [45]:
regressor = RandomForestRegressor(n_estimators = 20, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=20, random_state=0)

In [46]:
y_pred = regressor.predict(X_test)
y_pred

array([27166.25, 42538.75, 54061.25, ..., 42288.75, 55981.25, 43703.75])

In [39]:
#Calculate the MSE and MAE
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
#Print the results
print('Random Forest Regression:')
print('MSE:', mse)
print('MAE:', mae)

Random Forest Regression:
MSE: 62143.41875
MAE: 190.82215


In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
# determine the best value of the RF hyperparameter
clf = GridSearchCV(RandomForestRegressor(), {
    'n_estimators': [10,20,30],
    'max_depth': [1,2,4,6,7,8,9,10],
}, cv=5, return_train_score=False)
clf.fit(X_train,y_train)

In [ ]:
rfCV = pd.DataFrame(clf.cv_results_)

In [ ]:
rfCV

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.678307      0.013400         0.016705        0.000388   
1        1.533671      0.301295         0.035915        0.008863   
2        2.280649      0.501859         0.045903        0.008016   
3        1.632892      0.466568         0.029111        0.009942   
4        2.566036      0.259607         0.048040        0.005146   
5        4.539949      0.948199         0.071431        0.010221   
6        2.355798      0.346499         0.035199        0.000336   
7        4.688021      0.389221         0.069732        0.007333   
8        6.981761      0.349006         0.102779        0.010114   
9        3.299110      0.441395         0.049706        0.000956   
10       7.156889      0.518789         0.097975        0.009108   
11       9.773373      0.278621         0.145142        0.016431   
12       3.565725      0.177973         0.059617        0.004503   
13       7.173415      0.407248         0.109284        0.001254   
14      10.691829      0.307487         0.168696        0.012558   
15       4.055533      0.236024         0.071208        0.006924   
16       8.110758      0.409502         0.128618        0.002083   
17      12.218253      0.086974         0.189925        0.001213   
18       4.418084      0.411071         0.077890        0.001117   
19       8.636437      0.450970         0.149276        0.001030   
20      12.937876      0.091384         0.229672        0.012611   
21       4.688714      0.447737         0.091245        0.003846   
22       9.587317      0.552972         0.181640        0.011706   
23      14.073614      0.217152         0.267297        0.019047   

   param_max_depth param_n_estimators                                 params  \
0                1                 10   {'max_depth': 1, 'n_estimators': 10}   
1                1                 20   {'max_depth': 1, 'n_estimators': 20}   
2                1                 30   {'max_depth': 1, 'n_estimators': 30}   
3                2                 10   {'max_depth': 2, 'n_estimators': 10}   
4                2                 20   {'max_depth': 2, 'n_estimators': 20}   
5                2                 30   {'max_depth': 2, 'n_estimators': 30}   
6                4                 10   {'max_depth': 4, 'n_estimators': 10}   
7                4                 20   {'max_depth': 4, 'n_estimators': 20}   
8                4                 30   {'max_depth': 4, 'n_estimators': 30}   
9                6                 10   {'max_depth': 6, 'n_estimators': 10}   
10               6                 20   {'max_depth': 6, 'n_estimators': 20}   
11               6                 30   {'max_depth': 6, 'n_estimators': 30}   
12               7                 10   {'max_depth': 7, 'n_estimators': 10}   
13               7                 20   {'max_depth': 7, 'n_estimators': 20}   
14               7                 30   {'max_depth': 7, 'n_estimators': 30}   
15               8                 10   {'max_depth': 8, 'n_estimators': 10}   
16               8                 20   {'max_depth': 8, 'n_estimators': 20}   
17               8                 30   {'max_depth': 8, 'n_estimators': 30}   
18               9                 10   {'max_depth': 9, 'n_estimators': 10}   
19               9                 20   {'max_depth': 9, 'n_estimators': 20}   
20               9                 30   {'max_depth': 9, 'n_estimators': 30}   
21              10                 10  {'max_depth': 10, 'n_estimators': 10}   
22              10                 20  {'max_depth': 10, 'n_estimators': 20}   
23              10                 30  {'max_depth': 10, 'n_estimators': 30}   

    split0_test_score  split1_test_score  split2_test_score  \
0            0.386763           0.384055           0.381593   
1            0.386764           0.384054           0.381593   
2            0.386760           0.384055           0.381592   
3            0.617212           0.618618          

In [ ]:
rfCV[['param_n_estimators','params','mean_test_score']]

param_n_estimators                                 params  mean_test_score
0                  10   {'max_depth': 1, 'n_estimators': 10}         0.383826
1                  20   {'max_depth': 1, 'n_estimators': 20}         0.383827
2                  30   {'max_depth': 1, 'n_estimators': 30}         0.383828
3                  10   {'max_depth': 2, 'n_estimators': 10}         0.617679
4                  20   {'max_depth': 2, 'n_estimators': 20}         0.617681
5                  30   {'max_depth': 2, 'n_estimators': 30}         0.617682
6                  10   {'max_depth': 4, 'n_estimators': 10}         0.872174
7                  20   {'max_depth': 4, 'n_estimators': 20}         0.872197
8                  30   {'max_depth': 4, 'n_estimators': 30}         0.872518
9                  10   {'max_depth': 6, 'n_estimators': 10}         0.934503
10                 20   {'max_depth': 6, 'n_estimators': 20}         0.934708
11                 30   {'max_depth': 6, 'n_estimators': 30}         0.934928
12                 10   {'max_depth': 7, 'n_estimators': 10}         0.950716
13                 20   {'max_depth': 7, 'n_estimators': 20}         0.950917
14                 30   {'max_depth': 7, 'n_estimators': 30}         0.951027
15                 10   {'max_depth': 8, 'n_estimators': 10}         0.967263
16                 20   {'max_depth': 8, 'n_estimators': 20}         0.967574
17                 30   {'max_depth': 8, 'n_estimators': 30}         0.967578
18                 10   {'max_depth': 9, 'n_estimators': 10}         0.977807
19                 20   {'max_depth': 9, 'n_estimators': 20}         0.978057
20                 30   {'max_depth': 9, 'n_estimators': 30}         0.978070
21                 10  {'max_depth': 10, 'n_estimators': 10}         0.985040
22                 20  {'max_depth': 10, 'n_estimators': 20}         0.985391
23                 30  {'max_depth': 10, 'n_estimators': 30}         0.985473

In [ ]:
clf.best_params_

{'max_depth': 10, 'n_estimators': 30}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor

In [ ]:
clf1 = RandomizedSearchCV(RandomForestRegressor(), {
    'n_estimators': [10,20,30],
    'max_depth': [1,2,4,6,7,8,9,10],
}, cv=5, return_train_score=False)
clf1.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(),
                   param_distributions={'max_depth': [1, 2, 4, 6, 7, 8, 9, 10],
                                        'n_estimators': [10, 20, 30]})

In [ ]:
clf1.best_params_

{'n_estimators': 20, 'max_depth': 10}

In [ ]:
#clf1.cv_results_

In [ ]:
RmCV = pd.DataFrame(clf1.cv_results_)

In [ ]:
RmCV[['param_n_estimators','params','mean_test_score']]

param_n_estimators                                 params  mean_test_score
0                 10  {'n_estimators': 10, 'max_depth': 10}         0.985023
1                 10   {'n_estimators': 10, 'max_depth': 8}         0.967276
2                 10   {'n_estimators': 10, 'max_depth': 4}         0.872623
3                 20   {'n_estimators': 20, 'max_depth': 6}         0.934457
4                 30   {'n_estimators': 30, 'max_depth': 6}         0.934994
5                 30   {'n_estimators': 30, 'max_depth': 4}         0.872691
6                 20   {'n_estimators': 20, 'max_depth': 8}         0.967513
7                 20  {'n_estimators': 20, 'max_depth': 10}         0.985375
8                 20   {'n_estimators': 20, 'max_depth': 1}         0.383828
9                 20   {'n_estimators': 20, 'max_depth': 4}         0.871822

In [ ]:
#RmCV.head()

In [ ]:
clf1.best_estimator_.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': 10,
 'max_features': 1.0,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 20,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [ ]:
print("Best n_estimators:", clf1.best_estimator_.get_params()["n_estimators"])
print("Best max_depth:", clf1.best_estimator_.get_params()["max_depth"])

Best n_estimators: 20
Best max_depth: 10


In [ ]:
clf1.score(X_test, y_test)

In [ ]:
regressor1.predict([[190,2,4,4,1,0,0,1,3,1,1,1,1,0,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([74025.])

In [ ]:
a = int(input("What is the code of the Area?"))

What is the code of the Area?63


In [ ]:
b = int(input("How many garages?"))
f = int(input("How many Fire Place?"))
c = int(input("How many bathrooms?"))
e = int(input("Does the house have White Marble?"))
d = int(input("Does the house have Black Marble?"))
e1 = int(input("Does the house have Indian marble?"))
floors = int(input("How many floors?"))
city = int(input("What is the code of the city?"))
solar = int(input("Does the house have solar?"))
Electric = int(input("Does the house have Electric?"))
Fiber = int(input("Does the house have Fiber?"))
GlassDoors = int(input("Does the house have Glass Doors?"))
SwimingPool = int(input("Does the house have Swiming Pool?"))
Garden = int(input("Does the house have Garden?"))



How many garages?3
How many Fire Place?1
How many bathrooms?3
Does the house have White Marble?0
Does the house have Black Marble?0
Does the house have Indian marble?1
How many floors?2
What is the code of the city?3
Does the house have solar?0
Does the house have Electric?1
Does the house have Fiber?0
Does the house have Glass Doors?1
Does the house have Swiming Pool?1
Does the house have Garden?1


In [ ]:
regressor1.predict([[a,b,f,c,e,d,e1,floors,city,solar,Electric,Fiber,GlassDoors,SwimingPool,Garden]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([43000.])

In [ ]:
dataset.head()

Area  Garage  FirePlace  Baths  White Marble  Black Marble  Indian Marble  \
0   164       2          0      2             0             1              0   
1    84       2          0      4             0             0              1   
2   190       2          4      4             1             0              0   
3    75       2          4      4             0             0              1   
4   148       1          4      2             1             0              0   

   Floors  City  Solar  Electric  Fiber  Glass Doors  Swiming Pool  Garden  \
0       0     3      1         1      1            1             0       0   
1       1     2      0         0      0            1             1       1   
2       0     2      0         0      1            0             0       0   
3       1     1      1         1      1            1             1       1   
4       1     2      1         0      0            1             1       1   

   Prices  
0   43800  
1   37550  
2   49500  
3   50075  
4   52400